clients:
  - url: http://loki:3100/loki/api/v1/push  # Adjust the URL as needed
    timeout: 10s
positions:
  filename: /tmp/positions.yaml
labels:
  job: "multiverseroles-flask-app"
scrape_configs:
  - job_name: "multiverseroles-flask-app"
    static_configs:
      - targets:
          - "flask-app:5000"
    labels:
      __path__: "/app/logs/*.log"
